"""add source column to traces

Revision ID: 8ce02effe458
Revises: c6e81317ac0b
Create Date: 2026-07-12 14:47:57.715935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce02effe458'
down_revision: Union[str, Sequence[str], None] = 'c6e81317ac0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traces', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traces', 'source')
    # ### end Alembic commands ###
