"""replace definition with config fields

Revision ID: b0dc1d6a6f00
Revises: 1c08c4a2963d
Create Date: 2026-07-08 00:24:33.176746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0dc1d6a6f00'
down_revision: Union[str, Sequence[str], None] = '1c08c4a2963d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('system_prompt', sa.Text(), nullable=False))
    op.add_column('agents', sa.Column('tools', sa.JSON(), nullable=False))
    op.add_column('agents', sa.Column('model', sa.String(), nullable=False))
    op.add_column('agents', sa.Column('max_steps', sa.Integer(), nullable=True))
    op.drop_column('agents', 'definition')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('definition', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('agents', 'max_steps')
    op.drop_column('agents', 'model')
    op.drop_column('agents', 'tools')
    op.drop_column('agents', 'system_prompt')
    # ### end Alembic commands ###
