"""split token tracking into input and output

Revision ID: c6e81317ac0b
Revises: de35b46d30a9
Create Date: 2026-07-11 22:32:14.171703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e81317ac0b'
down_revision: Union[str, Sequence[str], None] = 'de35b46d30a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('runs', sa.Column('output_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'output_tokens')
    op.drop_column('runs', 'input_tokens')
    # ### end Alembic commands ###
